### PR TITLE
add percy

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by fotinakis** [comment]
Ok, the bug should be fixed! Can you try against master? (Need to some testing with a few customers before we will tag this as an official release)
```
npm install --save-dev git://github.com/percy/ember-percy#master
```

If you're curious, the bug was that we were only setting up ember-percy's finalizer IFF you had called `percySnapshot` once. Because your test suite was parallelized and had limited percySnapshot usage, the finalizer was only set up once in the partition that was using percySnapshot. The fix (here: https://github.com/percy/ember-percy/commit/a2ff735d43006e7b6f717402adc7553bbbfaf61c) was to move our internal finalization to always be called, no matter what, using a `content-for 'test-body-footer'` ember addon hook).

Let me know if that works!

**Comment by kellyselden** [comment]
Looks great now. Thanks Mike! Longstanding PR now merged 😄

**Comment by fotinakis** [comment]
👍

**Comment by fotinakis** [comment]
FYI, the fix is now released as ember-percy v1.2.1.

**Comment by kellyselden** [comment]
@fotinakis I rewrote the commit to put the real version number in, and now it seems to be hung again.

**Comment by fotinakis** [comment]
Oof sorry about that, there was a transient networking error (https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/161520196). If you click rebuild in travis or push a new commit it should work.

**Comment by kellyselden** [comment]
@fotinakis I restarted the entire Travis build last night and this morning, and percy is still hanging. I haven't tried rewriting the commit yet, because I wanted to give you a chance to debug if there is another hidden issue.

**Comment by fotinakis** [comment]
Damn, it looks like Travis re-uses build numbers when you click "restart" in the UI ... so that makes it very hard for us to tell the difference between builds when aggregate from parallel builds.

So, can you `git commit --allow-empty -m 'Rebuild.'` and push? Or merge from master or rebase or anything that will trigger a new Travis build other than clicking the button. :|

**Comment by kellyselden** [comment]
All good now, thanks @fotinakis

**Pull request merged**
